CREATE TABLE employee
(
    employee_id   INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    first_name    VARCHAR(30)         NOT NULL,
    last_name     VARCHAR(30)         NOT NULL,
    date_of_birth DATE                NOT NULL,
    email         VARCHAR(100) UNIQUE NOT NULL,
    username      VARCHAR(30) UNIQUE  NOT NULL,
    password      VARCHAR(50)         NOT NULL,
    role          VARCHAR(30)         NOT NULL,
    created_at    TIMESTAMP           NOT NULL,
    created_who   VARCHAR(30)         NOT NULL,
    updated_at    TIMESTAMP,
    updated_who   VARCHAR(30)
);

CREATE TABLE business_process
(
    process_id  INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title       VARCHAR(30) UNIQUE NOT NULL,
    created_at  TIMESTAMP          NOT NULL,
    created_who VARCHAR(30)        NOT NULL,
    updated_at  TIMESTAMP,
    updated_who VARCHAR(30)
);

CREATE TABLE process_stage
(
    stage_id     INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title        VARCHAR(30) NOT NULL,
    stage_result BOOLEAN,
    process_id   INT REFERENCES business_process (process_id) ON DELETE CASCADE
);

CREATE TABLE process_action
(
    action_id     INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    resolution    VARCHAR(30),
    action_result BOOLEAN,
    stage_id      INT REFERENCES process_stage (stage_id) ON DELETE CASCADE,
    task_owner_id INT REFERENCES employee (employee_id) ON DELETE RESTRICT
);

