CREATE TABLE Users
(
    id            int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    first_name    VARCHAR(30)  NOT NULL,
    last_name     VARCHAR(30)  NOT NULL,
    date_of_birth DATE         NOT NULL,
    email         VARCHAR(100) NOT NULL,
    username      VARCHAR(30)  NOT NULL,
    password      VARCHAR(50)  NOT NULL,
    role          VARCHAR(100) NOT NULL,
    created_at    TIMESTAMP,
    updated_at    TIMESTAMP,
    created_who   VARCHAR(100)
);