CREATE TABLE stage_relation
(
    stage_relation_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title             VARCHAR(70) NOT NULL,
    from_stage        INT REFERENCES stage (stage_id) ON DELETE CASCADE,
    to_stage          INT REFERENCES stage (stage_id) ON DELETE CASCADE,
    created_at        TIMESTAMP   NOT NULL,
    created_who       INT         NOT NULL,
    updated_at        TIMESTAMP,
    updated_who       INT DEFAULT NULL
);

