CREATE TABLE role
(
    role_id     INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    role_name   VARCHAR(30) UNIQUE NOT NULL,
    created_at  TIMESTAMP          NOT NULL,
    created_who INT                NOT NULL,
    updated_at  TIMESTAMP,
    updated_who INT DEFAULT NULL,
    FOREIGN KEY (updated_who) REFERENCES bp_user (user_id)
);

INSERT INTO role (role_name, created_at, created_who)
VALUES ('ADMIN', '2023-02-07 00:00:00-00', 1),
       ('USER', '2023-02-07 00:00:00-00', 1),
       ('EMPLOYEE', '2023-02-07 00:00:00-00', 1),
       ('MANAGER', '2023-02-07 00:00:00-00', 1),
       ('DIRECTOR', '2023-02-07 00:00:00-00', 1);

ALTER TABLE bp_user
    DROP COLUMN user_role;


